entries:
- title: Sidebar
  product: Prod
  folders:

  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage.html
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage.html
      output: pdf
      type: frontmatter

  - title: Getting Started
    output: web, pdf
    folderitems:
    - title: Prod generelt
      url: /prod.html
      output: web

    - title: Brannmursåpninger
      url: /brannmur.html
      output: web, pdf
